name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc clang-format

      - name: Check clang-format
        run: |
          echo "Checking source files format..."
          files=$(find . -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) -not -path "./build/*")
          for file in $files; do
              echo "Checking $file"
              clang-format --dry-run --Werror "$file"
          done

      - name: Configure project
        env:
          CC: gcc-14
          CXX: g++-14
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: cd build && ctest --verbose
